# Generated by Django 3.1.2 on 2020-11-02 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_batch', models.CharField(max_length=20)),
                ('item_quantity', models.FloatField()),
                ('item_price', models.FloatField()),
                ('item_total', models.FloatField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('retail_id', models.CharField(max_length=20)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanager.items')),
            ],
        ),
    ]
