# Generated by Django 3.1.2 on 2020-11-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_batch', models.CharField(max_length=20)),
                ('item_quantity', models.FloatField()),
                ('item_price', models.FloatField()),
                ('item_total', models.FloatField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanager.items')),
            ],
        ),
        migrations.CreateModel(
            name='RetailID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_id', models.CharField(max_length=200, unique=True)),
                ('item_quantity', models.FloatField()),
                ('item_price', models.FloatField()),
                ('expiry', models.DateField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanager.items')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_quantity', models.FloatField()),
                ('sales_total', models.FloatField()),
                ('sales_date', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanager.items')),
                ('retail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanager.retailid')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100, unique=True)),
                ('vendor_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_quantity', models.FloatField()),
                ('return_total', models.FloatField()),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('return_reason', models.CharField(max_length=200)),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanager.sales')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_quantity', models.FloatField()),
                ('return_total', models.FloatField()),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('return_reason', models.CharField(max_length=200)),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanager.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='retail_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmanager.retailid'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor_id',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmanager.vendor'),
        ),
    ]
