# Generated by Django 3.1.2 on 2020-11-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_contact',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
