# Generated by Django 3.1.2 on 2020-11-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_quantity', models.FloatField()),
                ('return_total', models.FloatField()),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('return_reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_id', models.CharField(max_length=20)),
                ('sales_quantity', models.FloatField()),
                ('sales_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_quantity', models.FloatField()),
                ('return_total', models.FloatField()),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('return_reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_location', models.CharField(max_length=100)),
            ],
        ),
    ]
