# Generated by Django 3.1.2 on 2020-11-08 13:35

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0002_vendor_vendor_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_contact',
            field=phone_field.models.PhoneField(blank=True, help_text='Phone Number', max_length=31),
        ),
    ]
