# Generated by Django 3.1.2 on 2020-11-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0003_auto_20201108_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturn',
            name='purchase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanager.purchase', unique=True),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='sales_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanager.sales', unique=True),
        ),
    ]
